version: "3"
services:
  app:
    image: huulane/reclib
    restart: unless-stopped
    command: npm run online
    volumes:
      - ./logs:/app/logs
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - MONGO_HOST=mongo
    depends_on:
      - redis
      - mongo

  mongo:
    image: mongo
    restart: unless-stopped
    expose:
      - 27017
    volumes:
      - ./static/doubanBook.agz:/var/static/doubanBook.agz
      - ./static/mongorestore.sh:/docker-entrypoint-initdb.d/mongorestore.sh
      - mongo-volume:/data/db

  redis:
    image: redis
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - redis-volume:/data
volumes:
  mongo-volume:
  redis-volume:
